config/routes.rb
Rails.application.routes.draw do

  get 'admin/dashboard'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  post '/store' => 'api#store'
  post '/classify' => 'api#classify'
  post '/track' => 'api#track'
  resources :histories
  resources :trackings
  resources :tracked_images
  resources :labels do
    collection do
      patch :random_recluster
      patch :ordered_recluster
    end
  end

  resources :locations do
    member do
      get :current
    end
  end

  root "trackings#last"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :tracked_images
  has_many :trackings, through: :tracked_images
  validates_presence_of :name
  validates_uniqueness_of :name

  def to_s
    name
  end
end

app/models/tracked_image.rb
class TrackedImage < ApplicationRecord
  belongs_to :location
  has_many :trackings
  has_attached_file :image
  validates_attachment_file_name :image, :matches => [/png\Z/, /jpe?g\Z/]
  do_not_validate_attachment_file_type :image
  validates_attachment_content_type :image, not: true
end

app/models/tracking.rb
class Tracking < ApplicationRecord
  belongs_to :tracked_image
  has_one :location, through: :tracked_image
  delegate :image, to: :tracked_image

  def coords(ratio=1.0)
    [left, top, left+width, top+height].map{|v| (v*ratio).to_i.to_s}.join(",")
  end

  def emb
    self[:emb] && Marshal.load(self[:emb])
  end

  def emb=(val)
    self[:emb] = Marshal.dump(val)
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def dashboard
    @tracking_timeframe = 5
    @locations = Location.all
    @chart_data = @locations.map do |loc|
      {
        name: loc.name,
        data: (loc.tracked_images
          .where("created_at > ?", 10.hours.ago)
          .group_by_second(:created_at)
          .count)
      }
    end
  end
end

app/controllers/api_controller.rb
require 'fileutils'
class ApiController < ApplicationController
  include LabelsHelper

  def track
    if params[:image]
      meta = JSON.parse(params[:data])
      location = Location.where(name: meta["location"]).first_or_create!
      tracked_image = TrackedImage.create(
          location: location,
          image: params[:image]
      )
      tracked_image.save!
      embs = meta['embeddings']
      unless embs
        puts "No Embedding sent"
        ec = EmbeddingClient.new
        embs = [ec.embed(params[:image])]
      end
      trackings = []
      tc = TrackingClient.new
      meta['positions'].each_with_index do |pos, ix|
        puts pos.inspect
        Tracking.transaction do
          tracking = Tracking.create(
              tracked_image: tracked_image,
              width:  pos['width'],
              height: pos['height'],
              left:   pos['left'],
              top:    pos['top'],
              emb:    embs[ix]
          )
          label = tc.track(tracking.id, embs[ix])
          tracking.label = label
          tracking.save!
          trackings << tracking
        end
      end
      render json: {
          label: trackings.map(&:label),
          location_url: current_location_url(id: location.name),
          colors: trackings.map(&:label).map{|l| label_color(l)[1..6]},
      }
    else
      render error: "No image given"
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  def show
    @trackings = Tracking.where(label: @label=params[:id]).order("created_at desc")
  end
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  def index
    @labels = Tracking.select("distinct(label)").map(&:label).map{|l| [l, Tracking.where(label: l).count]}.sort_by(&:last).reverse.to_h
  end

  def ordered_recluster
    trackings = Tracking.order("created_at")
    recluster_on(trackings)
  end

  def random_recluster
    trackings = Tracking.order("rand()")
    recluster_on(trackings, shuffled: true)
  end

  private
  def recluster_on(trackings, shuffled: false)
    tc = TrackingClient.new
    tc.reset
    trackings.find_in_batches(batch_size: 500) do |batch|
      batch.shuffle! if shuffled
      embs= batch.map &:emb
      ids = batch.map &:id
      resp = tc.track_batch(ids, embs)
      resp.each_with_index do |l,i|
        t = batch[i]
        t.label = l
        puts l
        t.save!
      end
    end

    redirect_to labels_path
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    @locations = Location.all
  end
  def show
    unless @location = Location.where(name: params[:id]).first
      @location = Location.find(params[:id])
    end
  end
  def current
    @loc_name = params[:id]
    if @location = Location.where(name: @loc_name).first
      @tracking = @location.trackings.last
      base_scope = Tracking.where(label: @tracking.label).
          where.not(id: @tracking.id).
          includes(:tracked_image, :location).
          order("rand()")
      num_images = 6
      @history  = base_scope.
          joins(:tracked_image).
          where.not(tracked_images: {location_id: @tracking.location.id}).
          first(num_images)
      count = @history.size
      if count < num_images
        @history += base_scope.first(num_images - count)
      end
    end
  end

end

app/controllers/tracked_images_controller.rb
class TrackedImagesController < ApplicationController

  def show
    @tracked_image = TrackedImage.find(params[:id])
  end
end

app/controllers/trackings_controller.rb
class TrackingsController < ApplicationController
  def index
    @trackings = Tracking.order("created_at desc").first(50)
  end

  def last
    @tracking = Tracking.order("created_at desc").first!
    render 'show'
  end

  def show
    @tracking = Tracking.find(params[:id])
  end
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
  def label_color(label)
    Colorizer.colorize(label)
  end
end

app/helpers/locations_helper.rb
module LocationsHelper
  def location_color(location)
    Colorizer.colorize(location.id)
  end
end

app/views/admin/dashboard.html.slim
.card
  .card-section
    h1= "Trackings within last #{@tracking_timeframe} seconds"
  .card-section
    = line_chart @chart_data

app/views/histories/_list.html.slim
.row.medium-up-2.large-up-3
  - trackings.each do |tracking|
    .column
      .card
        .card-divider
          span.label style="background-color:#{location_color(tracking.location)}"=tracking.location
        = render partial: 'shared/tracking_with_map', locals: {tracking: tracking, target_width: 369}
        .card-section
          =link_to tracking.created_at, tracking

app/views/histories/show.html.slim
h1= "History for #{@label}"

= render partial: 'histories/list', locals: {trackings: @trackings}

app/views/labels/index.html.slim
h1 Labels

table
  - @labels.each do |label, count|
    tr
      td
        span.label style="background-color:#{label_color(label)}"
          b=label
          =< "(#{count})"
      td
        a href=history_path(label)
          .row.medium-up-4.large-up-6
            - Tracking.where(label: label).last(6).reverse.each do |tracking|
              .column
                = render partial: 'shared/tracking_with_map', locals: {tracking: tracking, target_width: 170}

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Face Tracking" %></title>
    <%= yield(:header) %>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= render partial: "shared/nav" %>
    <%= yield %>

  </body>
</html>

app/views/locations/current.html.slim
.row
  .large-12.columns.text-center
    h1=@loc_name

- if @location
  = render partial: 'histories/list', locals: {trackings: @history}
- else
  .callout.warning
    |No Images recorded

- content_for :header do
  meta http-equiv="refresh" content="2"

app/views/locations/index.html.slim
h1 Locations

.row.medium-up-1.large-up-2
  - @locations.each do |loc|
    .column
      - if tracking = loc.tracked_images.last
        .card
          .card-divider
            span.label=loc
          = render partial: 'shared/tracked_image_with_map', locals: {tracked_image: tracking, target_width: 568}
          .button-group.expanded
            = link_to "Show all #{loc.trackings.count}", location_path(id: loc.name), class: "button"
            = link_to "Current", current_location_path(id: loc.name), class: "button"
            = link_to l(tracking.created_at), tracking, class: "button"

app/views/locations/show.html.slim
h1= "Trackings in Location #{@location}"

.row.medium-up-1.large-up-2
  - @location.tracked_images.each do |tracked_image|
    .column
      .card
        = render partial: 'shared/tracked_image_with_map', locals: {tracked_image: tracked_image, target_width: 568}
      .card-section
        =link_to tracked_image.created_at, tracked_image

app/views/shared/_nav.html.slim
.top-bar.show-for-large
  .top-bar-left
    ul.dropdown.menu data-dropdown-menu="" 
      li.menu-text Face Recognition
      li
        a href="/"  Home
      li
        a href="/labels" Labels
      li
        a href="/trackings" Trackings
      li
        a href="/locations" Locations
      li
        a href="/admin/dashboard" Dashboard
  .top-bar-right
    ul.menu
      li= link_to "Ordered Recluster!", ordered_recluster_labels_path, method: :patch, class: "button"
      li= link_to "Random Recluster!", random_recluster_labels_path, method: :patch, class: "button"

app/views/shared/_tracked_image_with_map.html.slim
- mapid = SecureRandom.hex
- real_width = 640
- target_width ||= real_width
- ratio = target_width.to_f / real_width
- classes = ["facemap"]
= image_tag tracked_image.image.url, usemap: "##{mapid}", width: target_width, class: classes.join(' ')
map name=mapid
  - tracked_image.trackings.each do |tracking|
    area shape="rect" coords=tracking.coords(ratio) href=history_path(tracking.label) title="#{tracking.label}" data-maphilight='{"strokeColor":"#{label_color(tracking.label)[1..6]}","strokeWidth":3,"fill":false,"alwaysOn":true}'

app/views/shared/_tracking_with_map.html.slim
- mapid = SecureRandom.hex
- # real_width = Paperclip::Geometry.from_file(tracking.image).width
- real_width = 640
- real_height= 480
- target_width ||= real_width
- ratio = target_width.to_f / real_width
- classes = ["facemap"]
- if local_assigns[:extra_classes]
  - classes |= local_assigns[:extra_classes]
= image_tag tracking.image.url, usemap: "##{mapid}", width: target_width, height: real_height*ratio, class: classes.join(' ')
map name=mapid
  area shape="rect" coords=tracking.coords(ratio) href=history_path(tracking.label) title="#{tracking.label}" data-maphilight='{"strokeColor":"#{label_color(tracking.label)[1..6]}","strokeWidth":3,"fill":false,"alwaysOn":true}'

app/views/tracked_images/show.html.slim
- if @tracked_image
  .card
    = render partial: 'shared/tracked_image_with_map', locals: {tracked_image: @tracked_image}
    .card-section
      p=@tracked_image.created_at
    .card-section
      p
        b
          |Location:
          =<@tracked_image.location
- else
  p No trackings yet

app/views/trackings/index.html.slim
h1 Trackings

table.table
  tbody
    - @trackings.each do |tracking|
      tr
        td
          span.label  style="background-color:#{label_color(tracking.label)}"
            =tracking.label
        td
          a href=history_path(tracking.label) style= "display: inline-block; border: 5px solid #{label_color(tracking.label)}"
            = render partial: 'shared/tracking_with_map', locals: {tracking: tracking}
        td=tracking.created_at
        td=tracking.location

app/views/trackings/last.html.slim
- if @tracking
  .card
    .card-divider
      h1
        |Last Tracking
        span.label=@tracking.label
    = render partial: 'shared/tracking_with_map', locals: {tracking: @tracking}
    .card-section
      p=@tracking.created_at
    .card-section
      p
        b
          |Location:
          =<@tracking.location
- else
  p No trackings yet

app/views/trackings/show.html.slim
- if @tracking
  .card
    .card-divider
      h1
        |Last Tracking
        span.label=@tracking.label
    = render partial: 'shared/tracking_with_map', locals: {tracking: @tracking}
    .card-section
      p=@tracking.created_at
    .card-section
      p
        b
          |Location:
          =<@tracking.location
- else
  p No trackings yet